package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # APACHE

java_import(
    name = "protoc-jar-maven-plugin",
    jars = ["protoc-jar-maven-plugin-3.5.1.2-batfish-internal.jar"],
)
